# Generated by Django 4.1.4 on 2022-12-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employees", name="PhotoFileName",),
    ]
