# Generated by Django 4.1.4 on 2022-12-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0002_remove_employees_photofilename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("DepartmentlId", models.AutoField(primary_key=True, serialize=False)),
                ("DepartmentlName", models.CharField(max_length=500)),
                ("NumOFEmployees", models.IntegerField(max_length=500)),
                ("EmployeeName", models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(name="Hotels",),
    ]
