# Generated by Django 4.1.4 on 2022-12-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0004_rename_department_employees_departmentname_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="HotelGuest", new_name="HotelGuests",),
        migrations.RenameField(
            model_name="departments", old_name="DepartmentlId", new_name="DepartmentId",
        ),
        migrations.RenameField(
            model_name="departments",
            old_name="DepartmentlName",
            new_name="DepartmentName",
        ),
        migrations.RenameField(
            model_name="payments", old_name="ReservationsID", new_name="ReservationID",
        ),
        migrations.RenameField(
            model_name="reservations",
            old_name="ReservationsEmailAddr",
            new_name="ReservationEmailAddr",
        ),
        migrations.RenameField(
            model_name="reservations",
            old_name="ReservationsID",
            new_name="ReservationID",
        ),
        migrations.RemoveField(model_name="rooms", name="id",),
        migrations.AlterField(
            model_name="employees", name="SSN", field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="RoomNum",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
