# Generated by Django 4.1.4 on 2022-12-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0005_rename_hotelguest_hotelguests_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="employees", name="DOB",),
        migrations.RemoveField(model_name="employees", name="DateOfJoining",),
    ]
